# Generated by Django 2.2.3 on 2020-04-16 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iamdbApp', '0002_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contentId', models.IntegerField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='iamdbApp.AuthUser')),
            ],
            options={
                'managed': True,
                'unique_together': {('user', 'contentId')},
            },
        ),
    ]
