# Generated by Django 2.2.3 on 2020-04-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamdbApp', '0003_wishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='contentId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='contentId',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
